JlptVocabulary.delete_all

JlptVocabulary.create(id: 100, kanji: '嗚呼', hiragana: 'ああ', english: ['Ah!','Oh!','Alas!'], level: 1)
JlptVocabulary.create(id: 101, kanji: '相', hiragana: 'あい', english: ['together','mutually','fellow'], level: 1)
JlptVocabulary.create(id: 102, kanji: '相変わらず', hiragana: 'あいかわらず', english: ['as ever','as usual','the same'], level: 1)
JlptVocabulary.create(id: 103, kanji: '愛想', hiragana: 'あいそ', english: ['civility','courtesy','compliments','sociability','graces'], level: 1)
JlptVocabulary.create(id: 104, kanji: '相対', hiragana: 'あいたい', english: ['confrontation','facing','between ourselves','no third party','tete-a-tete'], level: 1)
JlptVocabulary.create(id: 105, kanji: '間柄', hiragana: 'あいだがら', english: ['relation(ship)'], level: 1)
JlptVocabulary.create(id: 106, kanji: '愛憎', hiragana: 'あいにく', english: 'likes and dislikes', level: 1)
JlptVocabulary.create(id: 107, kanji: '合間', hiragana: 'あいま', english: 'interval', level: 1)
JlptVocabulary.create(id: 108, kanji: '曖昧', hiragana: 'あいまい', english: ['vague','ambiguous'], level: 1)
JlptVocabulary.create(id: 109, kanji: '敢えて', hiragana: 'あえて', english: ['dare (to do)','challenge (to do)'], level: 1)


JlptVocabulary.create(id: 200, kanji: '遭う', hiragana: 'あう', english: ['to meet','to encounter (undesirable nuance)'], level: 2)
JlptVocabulary.create(id: 201, kanji: '扇ぐ', hiragana: 'あおぐ', english: ['to fan','to flap'], level: 2)
JlptVocabulary.create(id: 202, kanji: '青白い', hiragana: 'あおじろい', english: ['pale','pallid'], level: 2)
JlptVocabulary.create(id: 203, kanji: '明き', hiragana: 'あおじろい', english: ['room','time to spare','emptiness'], level: 2)
JlptVocabulary.create(id: 204, kanji: '飽くまで', hiragana: 'あくまで', english: ['to the end','to the last','stubbornly'], level: 2)
JlptVocabulary.create(id: 205, kanji: '明け方', hiragana: 'あけがた', english: 'dawn', level: 2)
JlptVocabulary.create(id: 206, kanji: '揚げる', hiragana: 'あげる', english: ['to lift','to fry'], level: 2)
JlptVocabulary.create(id: 207, kanji: '挙げる', hiragana: 'あげる', english: ['to raise','to fly'], level: 2)
JlptVocabulary.create(id: 208, kanji: '憧れる', hiragana: 'あこがれる', english: ['to long for','to yearn after','to admire'], level: 2)
JlptVocabulary.create(id: 209, kanji: '足跡', hiragana: 'あしあと', english: 'footprints', level: 2)

JlptVocabulary.create(id: 300, kanji: '愛', hiragana: 'あい', english: 'love', level: 3)
JlptVocabulary.create(id: 301, kanji: '挨拶', hiragana: 'あいさつ', english: ['greetings', 'salutation'], level: 3)
JlptVocabulary.create(id: 302, kanji: '愛情', hiragana: 'あいじょう', english: ['love','affection'], level: 3)
JlptVocabulary.create(id: 303, kanji: '合図', hiragana: 'あいず', english: ['sign','signal'], level: 3)
JlptVocabulary.create(id: 304, kanji: '愛する', hiragana: 'あいする', english: 'to love', level: 3)
JlptVocabulary.create(id: 305, kanji: '相手', hiragana: 'あいて', english: ['companion','partner','company'], level: 3)
JlptVocabulary.create(id: 306, kanji: '明かり', hiragana: 'あかり', english: ['lamplight','light (in general)','brightness'], level: 3)
JlptVocabulary.create(id: 307, kanji: '空き', hiragana: 'あき', english: ['room','time to spare','emptiness'], level: 3)
JlptVocabulary.create(id: 308, kanji: '明らか', hiragana: 'あきらか', english: ['obvious','evident','clear'], level: 3)
JlptVocabulary.create(id: 309, kanji: '諦める', hiragana: 'あきらめる', english: ['to give up','to abandon'], level: 3)

JlptVocabulary.create(id: 400, kanji: '間', hiragana: 'あいだ', english: 'a space', level: 4)
JlptVocabulary.create(id: 401, kanji: '合う', hiragana: 'あう', english: 'to match', level: 4)
JlptVocabulary.create(id: 402, kanji: '上る', hiragana: 'あがる',	english: 'to rise', level: 4)
JlptVocabulary.create(id: 403, kanji: '赤ん坊', hiragana: 'あかんぼう', english: 'baby', level: 4)
JlptVocabulary.create(id: 404, kanji: '空く', hiragana: 'あく', english: ['to open','to become empty'], level: 4)
JlptVocabulary.create(id: 405, kanji: '浅い', hiragana: 'あさい',	english: ['shallow','superficial'], level: 4)
JlptVocabulary.create(id: 406, kanji: '味', hiragana: 'あじ', english: 'flavour', level: 4)
JlptVocabulary.create(id: 407, kanji: '明日', hiragana: 'あす', english: 'tomorrow', level: 4)
JlptVocabulary.create(id: 408, kanji: '遊び', hiragana: 'あそび',	english: 'play', level: 4)
JlptVocabulary.create(id: 409, kanji: '集る', hiragana: 'あつまる', english: 'to gather', level: 4)

JlptVocabulary.create(id: 500, kanji: '会う', hiragana: 'あう', english: 'to meet', level: 5)
JlptVocabulary.create(id: 501, kanji: '青', hiragana: 'あお', english: 'blue', level: 5)
JlptVocabulary.create(id: 502, kanji: '青い', hiragana: 'あおい', english: 'blue', level: 5)
JlptVocabulary.create(id: 503, kanji: '赤', hiragana: 'あか', english: 'red', level: 5)
JlptVocabulary.create(id: 504, kanji: '赤い', hiragana: 'あかい', english: 'red', level: 5)
JlptVocabulary.create(id: 505, kanji: '明い', hiragana: 'あかるい', english: 'bright', level: 5)
JlptVocabulary.create(id: 506, kanji: '秋', hiragana: 'あき', english: 'autumn', level: 5)
JlptVocabulary.create(id: 507, kanji: '開く', hiragana: 'あく', english: ['to open','to become open'], level: 5)
JlptVocabulary.create(id: 508, kanji: '開ける', hiragana: 'あける', english: 'to open', level: 5)
JlptVocabulary.create(id: 509, kanji: '上げる', hiragana: 'あげる', english: 'to give', level: 5)
